title: Sites
unlisted: false
tabs:
  main:
    columns:
      - width: 2/3
        sections:
          first_level:
            type: pages
            headline: Listed Pages
            query: site.pages.depth(1)
            status: listed
            layout: cards
            size: tiny
            image:
              query: page.cover.toFile
              cover: true
          second_level:
            type: pages
            headline: Unlisted Pages
            query: site.pages.depth(1)
            status: unlisted
            layout: cards
            size: tiny
            image:
              query: page.cover.toFile
              cover: true             
          last_level:
            type: pages
            headline: Unpublished Pages
            query: site.pages.depth(1)
            status: draft
            layout: cards
            size: tiny
            image:
              query: page.cover.toFile
              cover: true
      - width: 1/3
        sections:
          content:
            type: fields
            fields:
              analytics:
                label: Google Analytics Code
                type: textarea
                buttons: false
              toggle:
                label: Show logo
                type: toggle
                text: 
                  - "no"
                  - "yes"
              logo:
                label: Logo
                type: files
                max: 1
                when:
                  toggle: yes
              logo_text:
                label: Logo text
                type: text
                when:
                  toggle: no
              categories:
                label: Categories
                type: structure
                fields:
                  name:
                    type: text
                  description:
                    type: textarea
              xmlsitemap:
                label:     XML sitemap
                type:      toggle
                default:   off
                text:
                  - disabled
                  - enabled
  ads: 
    label: Ads
    type: tab
    fields:
      ad_code:
        label: Advertisement code
        type: textarea
        buttons: false
  seotab: seo
